name: Publish To Factorio Mod Portal

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Publish mod
        uses: Penguin-Spy/factorio-mod-portal-publish@main
        with:
          factorio-api-key: ${{ secrets.FACTORIO_API_KEY }}
